### ISSUE TITLE
please add DINC

### ISSUE THREAD

**Issue by hepsgs** [wavesnode/gateway-for-woocommerce#13]
hi, its a excellent plugin, please add asset DINC, thanks

Asset ID: HpcoMxTPz6vmACR2yzr16sKyQgcXfr1BvvfpFWWUZPB5            
Name: DINC

**Comment by tubbynl** [comment]
you can configure your own asset via the settings in the plugin
* set shop currency to EUR or USD (WooCommerce -> Settings -> general)
* set assetID code and description (WooCommerce -> Settings -> Checkout -> Waves)
* check checkbox "Convert prices..."

exchange rates are calculated via EUR/USD -> Waves  and then Waves -> Your asset

**Comment by clipto** [comment]
Also, make sure to check our blogpost with all info, tips & tricks:

https://wavesnode.net/blog/waves-woocommerce-gateway/
