### ISSUE TITLE
CHECKOUT BUTTON NOT SHOWING

### ISSUE THREAD

**Issue by akinolaking** [wavesnode/gateway-for-woocommerce#15]
Hi, I observed that when Waves Woocmmerce plugin is active on our website, Checkout button is not showing but when disactivated the button shows. I noticed this with Woocomerce Version 3.3.5 on WordPress Version 4.9.5. Can anyone check to fix it?

**Comment by clipto** [comment]
Don't know this issue, might be a cache error?
Have you tried in another browser?
No conflicting plugins? (disable them all and start enabling them 1 by 1).
Or try it with another theme maybe?
