### ISSUE TITLE
Requiring - ETH, XRP, BTC prices

### ISSUE THREAD

**Issue by Madman199** [wavesnode/gateway-for-woocommerce#17]
Could you implement the ability to use the above assets please?

Do you have a asset code for a fixed price of $0.01 also?

**Comment by clipto** [comment]
Check our blogpost:
https://wavesnode.net/blog/waves-woocommerce-gateway/

Are Fiat or Crypto gateway coins supported?
No, Fiat or Crypto gateway currencies, such as USD, EURO, Turkish Lira, Ethereum, Litecoin, Zcash, Monero & Dash are not supported.
