### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by iontishina** [wavesnode/gateway-for-woocommerce#6]
after uploading and activating plugin i see white screen with:

ParseError thrown

syntax error, unexpected end of file

https://imgur.com/a/2Lv3N

**Comment by tubbynl** [comment]
I’ll need to lookin on it; can you also describe your settings (plug-in and used currency)

**Comment by tubbynl** [comment]
i can't reproduce this, perhaps @clipto can give it a try

reproduction (i think)

> before
> * wordpress+woocommerce website without gateway-for-woocommerce plugin installed
> 
> then
> * upload gateway-for-woocommerce plugin
> * activate gateway-for-woocommerce plugin
> 
> result
> * above error pops up
> 
> expected
> * working gateway-for-woocommerce plugin

perhaps we can see some more details if we can reproduce it

**Comment by tubbynl** [comment]
perhaps @iontishina can zip the (gateway-for-woocommerce) plugin folder and provide it here, maybe it's partially incomplete

**Comment by clipto** [comment]
Please disable all other plugins, maybe there is one conflicting?
Do keep Woocommerce enabled ofcourse.

**Comment by aagjalpankaj** [comment]
It's a syntax error. 
@G1zm0nl  Avoid using "<?"

**Comment by tubbynl** [comment]
That would probably be my code ;) i’ll look into it

**Comment by tubbynl** [comment]
But you’ll probably run with short-tags-off?

**Comment by ThomasJetson** [comment]
Exact same issue for me also. Using EasyWP on Namecheap.com for Wordpress. 

UsingWordpress 4.9.5. Any assistance would be fantastic. Thank you.

**Comment by clipto** [comment]
Another client who had the same error fixed this with setting short-tags-on.
