### ISSUE TITLE
Php Version ?

### ISSUE THREAD

**Issue by michaelsomerville** [wavesnode/gateway-for-woocommerce#8]
I am looking for a solution to accept Waves Asset and post to a webhook, don't need all this stuff. Simple PHP script, can you build it ? We also are looking for someone to code a transfer/masspay as we can't seem to figure it out.

**Comment by michaelsomerville** [comment]
Got this working to test it in wordpress, we have trades on our token from us testing, but there isn't nothing showing here for data. Am I missing something ? ... the trades where on the mainnet via the client ( chrome ).


http://marketdata.wavesplatform.com/api/ticker/BCHNVrdxa29rgumNvowonj3UiLyfB89DG3GE6GmtNnq6/waves


```
{
  "symbol" : "",
  "amountAssetID" : "BCHNVrdxa29rgumNvowonj3UiLyfB89DG3GE6GmtNnq6",
  "amountAssetName" : "coinoutcome",
  "amountAssetDecimals" : 8,
  "amountAssetTotalSupply" : "21000000.00000000",
  "amountAssetMaxSupply" : "21000000.00000000",
  "amountAssetCirculatingSupply" : "10069.00000000",
  "priceAssetID" : "WAVES",
  "priceAssetName" : "WAVES",
  "priceAssetDecimals" : 8,
  "priceAssetTotalSupply" : "100000000.00000000",
  "priceAssetMaxSupply" : "100000000.00000000",
  "priceAssetCirculatingSupply" : "100000000.00000000",
  "24h_open" : "0.00000000",
  "24h_high" : "0.00000000",
  "24h_low" : "0.00000000",
  "24h_close" : "0.00000000",
  "24h_vwap" : "0.00000000",
  "24h_volume" : "0.00000000",
  "24h_priceVolume" : "0.00000000",
  "timestamp" : 1516330413741
}
```

**Comment by tubbynl** [comment]
These endpoints are only used for retrieving market info; actual trades are directly onto waves api
